
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: counter-service
  description: A simple counter service vi1234
  tags:
    - kotlin
spec:
  type: service
  lifecycle: experimental
  owner: group:guests
  system: counter-app
  providesApis: 
    - api:counter-api
